Fem1Bx = "MEGLAGYVYKAASEGKVLTLAALLLNRSESDIRYLLGYVSQQGGQRSTPLIIAARNGHAKVVRLLLEHYRVQTQQTGTVRFDGYVIDGATALWCAAGAGHFEVVKLLVSHGANVNHTTVTNSTPLRAACFDGRLDIVKYLVENNANISIANKYDNTCLMIAAYKGHTDVVRYLLEQRADPNAKAHCGATALHFAAEAGHIDIVKELIKWRAAIVVNGHGMTPLKVAAESCKADVVELLLSHADCDRRSRIEALELLGASFANDRENYDIIKTYHYLYLAMLERFQDGDNILEKEVLPPIHAYGNRTECRNPQELESIRQDRDALHMEGLIVRERILGADNIDVSHPIIYRGAVYADNMEFEQCIKLWLHALHLRQKGNRNTHKDLLRFAQVFSQMIHLNETVKAPDIECVLRCSVLEIEQSMNRVKNISDADVHNAMDNYECNLYTFLYLVCISTKTQCSEEDQCKINKQIYNLIHLDPRTREGFTLLHLAVNSNTPVDDFHTNDVCSFPNALVTKLLLDCGAEVNAVDNEGNSALHIIVQYNRPISDFLTLHSIIISLVEAGAHTDMTNKQNKTPLDKSTTGVSEILLKTQMKMSLKCLAARAVRANDINYQDQIPRTLEEFVGFH*VTGYVKSFNVVLKSKGLLITDSRIMCS"
AA = "ARNDCEQGHILKMFPSTWYV"

for i in range(len(AA)):
    Fem1Bxn=Fem1Bx.replace("*", AA[i])
    j=0
    
    with open("peptides.txt", "r") as rawpeplist:
        for line in rawpeplist:
                    
            words=line.split()
            if words[0] in Fem1Bxn:
                j=j+1
                print(words[0])
    print(i+1, j)